# Generated by Django 5.1.3 on 2024-12-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_taxi_passenger_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxi',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
