# Generated by Django 5.1.3 on 2024-12-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='meal_type',
        ),
    ]
